# List of particle types

particle_types:
# particles to be built into an event from .root files
  # follow the format:
  #   particle_name:
  #     class: 'path.to.particle.Particle'
  #     n_branch_name:  ROOT.TBranch (int) that could define how many particles to build
  #     conditioner: condition to filter the particles that want to be built
  #     sorter: how to sort the particles
  #       by: 'property' to sort by
  #       reverse: True/False to sort in reverse order
  # comment/uncomment/add as needed...
  digis:
    class: 'dtpr.particles.digi.Digi'
    n_branch_name: 'digi_nDigis'
    sorter:
      by: 'BX'
  segments:
    class: 'dtpr.particles.segment.Segment'
    n_branch_name: 'seg_nSegments'
  tps:
    class: 'dtpr.particles.ph2tp.Ph2tp'
    n_branch_name: 'ph2TpgPhiEmuAm_nTrigs'
  genmuons:
    class: 'dtpr.particles.gen_muon.GenMuon'
    n_branch_name: 'gen_nGenParts'
    conditioner: 
      property: 'gen_pdgId'
      condition: "==13"
    sorter:
      by: 'pt'
      reverse: True
  emushowers:
    class: 'dtpr.particles.shower.Shower'
    n_branch_name: 'ph2Shower_station'
  simhits:
    class: 'dtpr.particles.simhit.SimHit'
    n_branch_name: 'simHit_nSimHits'